#!/usr/bin/env node
// Export the design system's icons, app tiles and fox mark for the installer UI.
// Runs the design bundle (components/bundle.js) in a node vm, as described in
// docs/BUILD-SPEC.md §7, and writes:
//   assets/icons/<name>.svg          every design icon, stroke #151a21 (for other tools)
//   assets/tiles/<id>-light.svg      app tiles, Winter colours (appTileSVG)
//   assets/tiles/<id>-dark.svg       app tiles, Polar night colours
//   assets/mark-dark.svg / mark-light.svg   the fox mark with amber eyes
//   assets/Icons.js                  QML JS library: icon bodies + tile/app data, so
//                                    Icon.qml can recolour icons at runtime
// Usage: node dev/export-assets.js <path-to-design-project>   (dir containing components/bundle.js)
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const designDir = process.argv[2];
if (!designDir) {
  console.error('usage: export-assets.js <design project dir with components/bundle.js>');
  process.exit(2);
}
const bundle = fs.readFileSync(path.join(designDir, 'components', 'bundle.js'), 'utf8');
const ctx = { window: {}, document: {} };
vm.createContext(ctx);
vm.runInContext(bundle, ctx);
const A = ctx.window.Arctic;

const out = path.resolve(__dirname, '..', 'assets');
fs.mkdirSync(path.join(out, 'icons'), { recursive: true });
fs.mkdirSync(path.join(out, 'tiles'), { recursive: true });

// Token values (design/tokens.json, semantic colours) used by the tiles.
const TINT = {
  light: { 'info-soft': '#e2eefa', 'surface-sunken': '#e8edf1', 'slate-900': '#1a212a', 'warm-soft': '#f0eae3', 'accent-soft': '#fdf0d6', 'success-soft': '#e1f2e9', 'warning-soft': '#fbeadf' },
  dark: { 'info-soft': '#172c42', 'surface-sunken': '#0f141a', 'slate-900': '#1a212a', 'warm-soft': '#2f2924', 'accent-soft': '#3a2d16', 'success-soft': '#16322a', 'warning-soft': '#3a2518' },
};
const INK = { light: '#151a21', dark: '#e9eef3' };
const SNOW100 = '#f3f6f8';
// APP_TINT is not exported by the bundle; mirror it (bundle.js "APP_TINT").
const APP_TINT = { browser: 'info-soft', editor: 'surface-sunken', terminal: 'slate-900', shell: 'warm-soft', files: 'accent-soft', office: 'success-soft', video: 'warning-soft', extras: 'surface-sunken', system: 'surface-sunken' };

let n = 0;
for (const name of Object.keys(A.ICONS)) {
  fs.writeFileSync(path.join(out, 'icons', name + '.svg'), A.icon(name, { size: 24, color: '#151a21' }) + '\n');
  n++;
}

function tileSVG(id, theme) {
  const a = A.APPS[id];
  const tint = TINT[theme][APP_TINT[a[1]]];
  const ink = a[1] === 'terminal' ? SNOW100 : INK[theme];
  // Same geometry as the bundle's appTileSVG (64 box, rx 19 = 30%, glyph scaled 1.5).
  return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64"><rect width="64" height="64" rx="19" fill="' + tint + '"/>' +
    '<g transform="translate(14 14) scale(1.5)" fill="none" stroke="' + ink + '" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">' +
    A.ICONS[a[2]].replace(/currentColor/g, ink) + '</g></svg>\n';
}
let t = 0;
for (const id of Object.keys(A.APPS)) {
  const light = tileSVG(id, 'light');
  // Sanity: our light tile must equal the bundle's own appTileSVG output.
  if (light.trim() !== A.appTileSVG(id, 64).trim()) throw new Error('tile mismatch for ' + id);
  fs.writeFileSync(path.join(out, 'tiles', id + '-light.svg'), light);
  fs.writeFileSync(path.join(out, 'tiles', id + '-dark.svg'), tileSVG(id, 'dark'));
  t++;
}

fs.writeFileSync(path.join(out, 'mark-dark.svg'), A.mark({ size: 96, ink: '#e9eef3', eye: '#f6bd55' }) + '\n');
fs.writeFileSync(path.join(out, 'mark-light.svg'), A.mark({ size: 96, ink: '#151a21', eye: '#efa637' }) + '\n');

// QML JS library. `.pragma library` so it is shared by every Icon instance.
const icons = {};
for (const name of Object.keys(A.ICONS)) icons[name] = A.ICONS[name];
const apps = {};
for (const id of Object.keys(A.APPS)) {
  const a = A.APPS[id];
  apps[id] = { name: a[0], category: a[1], glyph: a[2], summary: a[3], default: a[4] };
}
const js = '.pragma library\n' +
  '// Generated by dev/export-assets.js from the Arctic design bundle. Do not edit.\n' +
  'var ICONS = ' + JSON.stringify(icons, null, 1) + ';\n' +
  'var APPS = ' + JSON.stringify(apps, null, 1) + ';\n' +
  'var CATEGORIES = ' + JSON.stringify(A.CATEGORIES) + ';\n' +
  'var STEP_NAMES = ' + JSON.stringify(A.STEP_NAMES) + ';\n' +
  '// Build an SVG data URI for icon `name` stroked with `color` (a #rrggbb string).\n' +
  'function svg(name, color, stroke) {\n' +
  '    var body = ICONS[name] || ICONS["help"];\n' +
  '    body = body.replace(/currentColor/g, color);\n' +
  '    var s = \'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="\' + color +\n' +
  '        \'" stroke-width="\' + (stroke || 1.75) + \'" stroke-linecap="round" stroke-linejoin="round">\' + body + "</svg>";\n' +
  '    return "data:image/svg+xml;utf8," + encodeURIComponent(s);\n' +
  '}\n';
fs.writeFileSync(path.join(out, 'Icons.js'), js);
console.log('icons: ' + n + ', tiles: ' + t + ' x2 themes, marks: 2, Icons.js written to ' + out);
