#!/usr/bin/env bash
# Regenerate the GRUB theme in branding/grub/arctic/ (live ISO boot menu and
# the installed system): theme.txt, background.png, mark.png, the selection /
# item / terminal 9-slices and the PF2 fonts.
#
# Design: design/exports/grub-theme.txt and the BootMenu component (Polar night).
set -euo pipefail
# shellcheck disable=SC2034  # read by ensure_tools in lib.sh
SCRIPT_ARGS=("$@")
# shellcheck source=branding/tools/lib.sh source-path=SCRIPTDIR
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
ensure_tools branding/tools/build-grub-theme.sh rsvg-convert grub2-mkfont

OUT="$BRANDING_DIR/grub/arctic"
FONTS="$BRANDING_DIR/fonts"
install -d "$OUT" "$BUILD_DIR"
rm -f "$OUT"/*.png "$OUT"/*.pf2

log "fonts + brand SVGs"
python3 "$TOOLS_DIR/fonts.py" "$DESIGN_DIR/fonts" "$FONTS" >/dev/null
python3 "$TOOLS_DIR/brand.py" "$BRANDING_DIR/src" "$FONTS" >/dev/null

log "background.png: aurora-polar-night 1920x1080 + 70% #0c1015"
render_svg "$DESIGN_DIR/wallpapers/aurora-polar-night.svg" "$BUILD_DIR/grub-aurora.png" 1920 1080
python3 "$TOOLS_DIR/grub_assets.py" background "$BUILD_DIR/grub-aurora.png" "$OUT/background.png"

log "mark.png: the polar-night lockup, 38 px tall (BootMenu wordmark(30))"
MARK_H=38
rsvg-convert -h "$MARK_H" -o "$OUT/mark.png" "$BRANDING_DIR/src/arctic-lockup-polar-night.svg"
MARK_W=$(python3 -c 'import sys; from PIL import Image; print(Image.open(sys.argv[1]).size[0])' "$OUT/mark.png")

log "9-slices"
python3 "$TOOLS_DIR/grub_assets.py" slices "$OUT"

log "PF2 fonts"
RANGE="0x20-0x7E,0xA0-0x17F,0x2010-0x2027,0x2039-0x203A,0x20AC-0x20AC,0x2122-0x2122,0x2190-0x2193,0x2212-0x2212"
mkfont() {  # OUT.pf2 SIZE TTF FAMILY-FOR-MKFONT FINAL-NAME [grub2-mkfont options]
    local out="$1" size="$2" ttf="$3" family="$4" name="$5"
    shift 5
    grub2-mkfont -r "$RANGE" -s "$size" -n "$family" "$@" -o "$OUT/$out" "$FONTS/$ttf"
    python3 "$TOOLS_DIR/grub_assets.py" pf2name "$OUT/$out" "$name"
}
# JetBrains Mono's hinting drops the dot of "i" (a dotlessi + dot composite)
# at 12-16 px in grub2-mkfont's monochrome rendering, and its computed
# descent clips g/p/y in the terminal: render it unhinted with a deeper descent.
mkfont figtree-medium-17.pf2   17 Figtree-Medium.ttf        "Figtree Medium"   "Figtree Medium 17"
mkfont figtree-semibold-17.pf2 17 Figtree-SemiBold.ttf      "Figtree SemiBold" "Figtree SemiBold 17"
mkfont jetbrains-mono-12.pf2   12 JetBrainsMono-Regular.ttf "JetBrains Mono"   "JetBrains Mono Regular 12" --no-hinting -d 4
mkfont jetbrains-mono-13.pf2   13 JetBrainsMono-Regular.ttf "JetBrains Mono"   "JetBrains Mono Regular 13" --no-hinting -d 4
mkfont jetbrains-mono-16.pf2   16 JetBrainsMono-Regular.ttf "JetBrains Mono"   "JetBrains Mono Regular 16" --no-hinting -c 13 -d 4

log "theme.txt"
cat > "$OUT/theme.txt" <<EOF
# Arctic Linux — GRUB theme (Polar night). Generated by branding/tools/build-grub-theme.sh.
# Design: design/exports/grub-theme.txt + the BootMenu component. The menu
# entries come from grub.cfg (ISO: Try / Install / Safe graphics / Check USB /
# Boot from first disk); this file only styles them.
#
# The selection pixmap is 16 px (text inset) x 10 px (radius) per corner and
# GRUB adds those pads around item_height, so item_height 20 draws 40 px
# rows; item_spacing 24 leaves the 4 px gap. item_* are transparent slices
# with the same pads so every label shares one baseline.
# grub.cfg must loadfont every *.pf2 here (grub2-mkconfig's 00_header does
# this for GRUB_THEME) and use gfxterm.

title-text: ""
desktop-image: "background.png"
desktop-image-scale-method: "crop"
desktop-color: "#0c1015"
terminal-font: "JetBrains Mono Regular 16"
terminal-box: "terminal_box_*.png"
terminal-left: "10%"
terminal-top: "10%"
terminal-width: "80%"
terminal-height: "80%"

+ image {
  top = 15%
  left = 50%-$((MARK_W / 2))
  width = $MARK_W
  height = $MARK_H
  file = "mark.png"
}

+ boot_menu {
  left = 50%-210
  top = 15%+$((MARK_H + 36))
  width = 420
  height = 272
  item_font = "Figtree Medium 17"
  selected_item_font = "Figtree SemiBold 17"
  item_color = "#e9eef3"
  selected_item_color = "#151a21"
  item_height = 20
  item_padding = 0
  item_spacing = 24
  item_icon_space = 0
  icon_width = 0
  icon_height = 0
  item_pixmap_style = "item_*.png"
  selected_item_pixmap_style = "select_*.png"
  scrollbar = false
}

+ label {
  id = "__timeout__"
  left = 0
  top = 100%-56
  width = 100%
  align = "center"
  font = "JetBrains Mono Regular 13"
  color = "#aeb9c5"
  text = "Starting in %d s"
}

+ label {
  left = 0
  top = 100%-32
  width = 100%
  align = "center"
  font = "JetBrains Mono Regular 12"
  color = "#8f9cab"
  text = "↑ ↓ choose · Enter start · e edit · c command line"
}
EOF

log "grub theme: $(du -sh "$OUT" | cut -f1) in branding/grub/arctic"
