# Arctic Linux — Polar night (kitty)
# include ~/.config/kitty/arctic-polar-night.conf

foreground             #dfe6ed
background             #151b22
cursor                 #f6bd55
cursor_text_color      #151b22
selection_foreground   #f3f6f9
selection_background   #5a4520
url_color              #86bdf5
active_border_color    #f6bd55
inactive_border_color  #2f3945
active_tab_foreground  #151a21
active_tab_background  #f6bd55
inactive_tab_foreground #aeb9c5
inactive_tab_background #0f141a

color0   #2a3440   # black
color1   #ef8a84   # red
color2   #7fcf9b   # green
color3   #f2b857   # yellow
color4   #80b0e8   # blue
color5   #d49ccf   # magenta
color6   #72cfd3   # cyan
color7   #c3ccd6   # white
color8   #8392a3   # bright-black
color9   #ffa39c   # bright-red
color10  #9ee6b6   # bright-green
color11  #ffd07f   # bright-yellow
color12  #a2c8f2   # bright-blue
color13  #e8b8e3   # bright-magenta
color14  #9be3e6   # bright-cyan
color15  #f3f6f9   # bright-white

font_family      JetBrains Mono
font_size        10.5
window_padding_width 10 12
cursor_shape     block
cursor_blink_interval 0
