#!/usr/bin/env python3
"""Generate the Arctic Linux desktop theme files from the design tokens.

Reads  design/exports/arctic-tokens.json  (flat export of design/tokens.json)
Writes dotfiles/.config/arctic/themes/{winter,polar-night}/  — one folder per theme:

  mango-colors.conf   Mango border/root colours + shadow colour
  kitty.conf          kitty palette, fonts and padding
  waybar-colors.css   @define-color lines for waybar/style.css
  gtk.css             GTK3/GTK4/libadwaita colour overrides
  mako.ini            full mako config (mako has no include)
  fuzzel-colors.ini   [colors] section included by fuzzel.ini
  swaylock.conf       full swaylock config
  theme.env           ARCTIC_THEME, colour scheme and wallpapers, sourced by arctic-* scripts
  theme.json          every token for the Quickshell desktop shell (shell/Theme.qml watches it)

and shell/assets/theme-defaults.js, the shell's built-in Polar night (used until a theme.json
can be read).
  icons/*.svg         design icons recoloured for the theme's ink, plus the 16px mark

Run from the repo root:  python3 design/tools/gen-desktop-themes.py
Only the Python standard library is used.
"""
import json
import os
import re
import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TOKENS = os.path.join(ROOT, "design", "exports", "arctic-tokens.json")
GTK_EXPORT = os.path.join(ROOT, "design", "exports", "gtk-arctic-{}.css")
ICONS_SRC = os.path.join(ROOT, "design", "icons")
LOGOS_SRC = os.path.join(ROOT, "design", "logos")
OUT = os.path.join(ROOT, "dotfiles", ".config", "arctic", "themes")
SHELL_DEFAULTS = os.path.join(ROOT, "shell", "assets", "theme-defaults.js")

THEMES = {
    # folder name: (token theme key, gsettings color-scheme, default wallpaper, lock wallpaper)
    "winter": ("light", "prefer-light", "snowfield-winter", "fox-winter"),
    "polar-night": ("dark", "prefer-dark", "aurora-polar-night", "fox-polar-night"),
}

# Icons that sit at rest in ink-muted (quiet bar items); everything else uses ink.
MUTED_ICONS = {"bell", "bell-off", "bluetooth"}

HEADER = "Generated by design/tools/gen-desktop-themes.py from design/tokens.json — do not edit by hand."


def rgba_hex(c, alpha=None):
    """#rrggbb or #rrggbbaa -> rrggbbaa (no #)."""
    c = c.lstrip("#")
    if len(c) == 6:
        c += "ff" if alpha is None else alpha
    elif alpha is not None:
        c = c[:6] + alpha
    return c.lower()


def css_rgba(c):
    """#rrggbbaa -> rgba(r, g, b, a) for GTK CSS, which lacks 8-digit hex on older GTK3."""
    c = c.lstrip("#")
    r, g, b = int(c[0:2], 16), int(c[2:4], 16), int(c[4:6], 16)
    a = int(c[6:8], 16) / 255 if len(c) == 8 else 1.0
    return "rgba({}, {}, {}, {:.2f})".format(r, g, b, a)


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def mango(t, key):
    shadow = "0x000000cc" if key == "dark" else "0x12171e33"
    return f"""# {HEADER}
# Mango colours are 0xRRGGBBAA.
rootcolor=0x{rgba_hex(t['ground'])}
bordercolor=0x{rgba_hex(t['line'])}
focuscolor=0x{rgba_hex(t['accent-edge'])}
urgentcolor=0x{rgba_hex(t['error'])}
maximizescreencolor=0x{rgba_hex(t['line'])}
scratchpadcolor=0x{rgba_hex(t['line-strong'])}
globalcolor=0x{rgba_hex(t['info'])}
overlaycolor=0x{rgba_hex(t['accent-soft'])}
dropcolor=0x{rgba_hex(t['accent'], '55')}
splitcolor=0x{rgba_hex(t['accent-edge'])}
shadowscolor={shadow}
"""


def kitty(t, term, key, name):
    ansi = "\n".join(
        "color{:<3} {}".format(i, c) for i, c in enumerate(term["ansi"])
    )
    return f"""# {HEADER}
# Arctic Linux — {name} (kitty)

foreground              {term['foreground']}
background              {term['background']}
cursor                  {term['cursor']}
cursor_text_color       {term['cursor_text_color']}
selection_foreground    {term['selection_foreground']}
selection_background    {term['selection_background']}
url_color               {t['info']}
active_border_color     {t['accent-edge']}
inactive_border_color   {t['line']}
bell_border_color       {t['warning']}
active_tab_foreground   {t['on-accent']}
active_tab_background   {t['accent']}
inactive_tab_foreground {t['ink-muted']}
inactive_tab_background {t['surface-sunken']}
tab_bar_background      {t['surface-sunken']}
mark1_background        {t['accent']}
mark1_foreground        {t['on-accent']}

{ansi}
"""


def waybar(t, key):
    names = ["ground", "surface", "surface-raised", "surface-sunken", "line", "line-strong",
             "ink", "ink-muted", "ink-subtle", "accent", "accent-hover", "accent-edge", "on-accent",
             "accent-soft", "focus", "success", "warning", "error", "info", "info-soft"]
    lines = ["/* {} */".format(HEADER)]
    lines.append("@define-color frost {};".format(css_rgba(t["frost"])))
    for n in names:
        lines.append("@define-color {} {};".format(n.replace("-", "_"), t[n]))
    return "\n".join(lines) + "\n"


def mako(t, key, name):
    # Notifications are opaque surface-raised cards (no frost); critical = error border, no timeout.
    return f"""# {HEADER}
# Arctic Linux — {name} (mako). Spec: components/Notification, components/OSD.
font=Figtree 10
width=340
height=160
margin=12
padding=12,16
border-size=1
border-radius=14
icons=1
max-icon-size=36
icon-location=left
background-color={t['surface-raised']}
text-color={t['ink']}
border-color={t['line']}
progress-color=over {t['accent']}
default-timeout=6000
ignore-timeout=0
layer=overlay
anchor=top-right
max-visible=4
format=<b>%s</b>\\n<span color="{t['ink-muted']}">%b</span>

[hidden]
format=<span color="{t['ink-subtle']}">%h more</span>

[urgency=critical]
border-color={t['error']}
default-timeout=0

[mode=do-not-disturb]
invisible=1

[mode=do-not-disturb urgency=critical]
invisible=0

# On-screen display for volume and brightness (arctic-osd): 280x48 pill, bottom centre.
[app-name=arctic-osd]
anchor=bottom-center
margin=44
width=280
height=48
padding=14,16
border-radius=24
background-color={t['frost']}
icons=1
max-icon-size=20
default-timeout=1200
format=<b>%s</b>
progress-color=over {t['accent']}
"""


def fuzzel(t, key):
    return f"""# {HEADER}
[colors]
background={rgba_hex(t['frost'])}
text={rgba_hex(t['ink'])}
prompt={rgba_hex(t['ink-muted'])}
placeholder={rgba_hex(t['ink-subtle'])}
input={rgba_hex(t['ink'])}
match={rgba_hex(t['accent-text'])}
selection={rgba_hex(t['accent-soft'])}
selection-text={rgba_hex(t['ink'])}
selection-match={rgba_hex(t['accent-text'])}
counter={rgba_hex(t['ink-subtle'])}
border={rgba_hex(t['line'])}
"""


def swaylock(t, key, lock_wp):
    c = lambda n: rgba_hex(t[n])
    return f"""# {HEADER}
# Arctic Linux lock screen (swaylock). Spec: components/LockScreen.
# Ring: focus while typing, error when wrong, success when verified.
# The wallpaper ({lock_wp}) is passed by arctic-lock with an absolute path.
scaling=fill
color={c('ground')}
font=Figtree
font-size=20
indicator-radius=72
indicator-thickness=6
indicator-idle-visible
show-failed-attempts
ignore-empty-password
daemonize

inside-color={rgba_hex(t['frost'])}
inside-clear-color={rgba_hex(t['frost'])}
inside-caps-lock-color={rgba_hex(t['frost'])}
inside-ver-color={c('success-soft')}
inside-wrong-color={c('error-soft')}
ring-color={c('line-strong')}
ring-clear-color={c('line-strong')}
ring-caps-lock-color={c('warning')}
ring-ver-color={c('success')}
ring-wrong-color={c('error')}
key-hl-color={c('focus')}
bs-hl-color={c('ink-muted')}
caps-lock-key-hl-color={c('warning')}
caps-lock-bs-hl-color={c('ink-muted')}
line-color=00000000
line-clear-color=00000000
line-caps-lock-color=00000000
line-ver-color=00000000
line-wrong-color=00000000
separator-color=00000000
text-color={c('ink')}
text-clear-color={c('ink-muted')}
text-caps-lock-color={c('warning')}
text-ver-color={c('success')}
text-wrong-color={c('error')}
layout-bg-color={rgba_hex(t['frost'])}
layout-border-color={c('line')}
layout-text-color={c('ink')}
"""


def theme_env(t, folder, key, scheme, wp, lock_wp, names):
    return f"""# {HEADER}
ARCTIC_THEME={folder}
ARCTIC_THEME_NAME="{names[key]}"
ARCTIC_GROUND="{t['ground']}"
ARCTIC_COLOR_SCHEME={scheme}
ARCTIC_GTK_PREFER_DARK={'1' if key == 'dark' else '0'}
ARCTIC_WALLPAPER={wp}
ARCTIC_LOCK_WALLPAPER={lock_wp}
"""


def camel(name):
    """design token name -> QML property name: surface-raised -> surfaceRaised, ansi-0 -> ansi0."""
    head, *rest = name.split("-")
    return head + "".join(p[:1].upper() + p[1:] for p in rest)


def qml_color(c):
    """#rrggbb stays; CSS #rrggbbaa -> QML #aarrggbb."""
    c = c.lower()
    if len(c) == 9:
        return "#" + c[7:9] + c[1:7]
    return c


def px(v):
    """'12px' -> 12, '120ms' -> 120, '-0.02em' -> -0.02 (numbers pass through)."""
    if isinstance(v, (int, float)):
        return v
    m = re.match(r"^(-?[0-9.]+)", str(v))
    n = float(m.group(1)) if m else 0
    return int(n) if n == int(n) else n


def bezier(v):
    """'cubic-bezier(0.2, 0, 0, 1)' -> [0.2, 0, 0, 1]."""
    return [px(x.strip()) for x in re.findall(r"\((.*)\)", v)[0].split(",")]


def theme_json(tok, folder, key, scheme, wp, lock_wp):
    """All tokens the Quickshell shell needs, in one file per theme (QML colour order)."""
    t = tok["themes"][key]
    colors = {camel(k): qml_color(v) for k, v in t.items()}
    for k, v in tok["ramps"].items():
        colors[camel(k)] = qml_color(v)
    return json.dumps({
        "_comment": HEADER + " Colours are QML #AARRGGBB.",
        "id": folder,
        "name": tok["themeNames"][key],
        "dark": key == "dark",
        "colorScheme": scheme,
        "wallpaper": wp,
        "lockWallpaper": lock_wp,
        "colors": colors,
        "fonts": dict(tok["font"]),
        "type": {camel(k): {"size": px(v["fontSize"]), "lineHeight": px(v["lineHeight"]),
                            "weight": v["fontWeight"], "family": v["family"],
                            "letterSpacing": px(v.get("letterSpacing", 0))}
                 for k, v in tok["type"].items()},
        "spacing": {camel(k.replace("-0-5", "Half")): px(v) for k, v in tok["spacing"].items()},
        "radius": {camel(k): px(v) for k, v in tok["radius"].items()},
        "border": {camel(k): px(v) for k, v in tok["border"].items()},
        "blur": {camel(k): px(v) for k, v in tok["blur"].items()},
        "size": {camel(k): px(v) for k, v in tok["size"].items()},
        "duration": {camel(k): px(v) for k, v in tok["duration"].items()},
        "easing": {camel(k): bezier(v) for k, v in tok["easing"].items()},
    }, indent=1, sort_keys=False) + "\n"


def icons(t, dest):
    os.makedirs(dest, exist_ok=True)
    for fn in sorted(os.listdir(ICONS_SRC)):
        if not fn.endswith(".svg"):
            continue
        with open(os.path.join(ICONS_SRC, fn), encoding="utf-8") as f:
            svg = f.read()
        ink = t["ink-muted"] if fn[:-4] in MUTED_ICONS else t["ink"]
        # The design exports icons in charcoal ink (#151a21); recolour stroke and fill.
        svg = re.sub(r"#151a21", ink, svg, flags=re.IGNORECASE)
        write(os.path.join(dest, fn), svg)
    # The accent (on-accent) variant used on the amber Install item.
    with open(os.path.join(ICONS_SRC, "download.svg"), encoding="utf-8") as f:
        write(os.path.join(dest, "download-on-accent.svg"),
              re.sub(r"#151a21", t["on-accent"], f.read(), flags=re.IGNORECASE))


def mark(key, dest):
    # The 16px drawing of the mark (no eyes, wider gap) for the bar: charcoal on Winter, snow on Polar night.
    src = os.path.join(LOGOS_SRC, "arctic-mark-16-{}.svg".format("snow" if key == "dark" else "charcoal"))
    shutil.copy(src, os.path.join(dest, "mark.svg"))


def main():
    with open(TOKENS, encoding="utf-8") as f:
        tok = json.load(f)
    for folder, (key, scheme, wp, lock_wp) in THEMES.items():
        t = tok["themes"][key]
        term = tok["terminal"][key]
        name = tok["themeNames"][key]
        d = os.path.join(OUT, folder)
        if os.path.isdir(d):
            shutil.rmtree(d)
        write(os.path.join(d, "mango-colors.conf"), mango(t, key))
        write(os.path.join(d, "kitty.conf"), kitty(t, term, key, name))
        write(os.path.join(d, "waybar-colors.css"), waybar(t, key))
        # GTK CSS has no 8-digit hex (#rrggbbaa), so translucent colours become rgba().
        with open(GTK_EXPORT.format(folder), encoding="utf-8") as f:
            gtk = re.sub(r"#([0-9a-fA-F]{8})\b", lambda m: css_rgba("#" + m.group(1)), f.read())
        write(os.path.join(d, "gtk.css"), gtk)
        write(os.path.join(d, "mako.ini"), mako(t, key, name))
        write(os.path.join(d, "fuzzel-colors.ini"), fuzzel(t, key))
        write(os.path.join(d, "swaylock.conf"), swaylock(t, key, lock_wp))
        write(os.path.join(d, "theme.env"), theme_env(t, folder, key, scheme, wp, lock_wp, tok["themeNames"]))
        write(os.path.join(d, "theme.json"), theme_json(tok, folder, key, scheme, wp, lock_wp))
        icons(t, os.path.join(d, "icons"))
        mark(key, os.path.join(d, "icons"))
        print("wrote", os.path.relpath(d, ROOT))
        if folder == "polar-night":
            # The shell's built-in fallback (used before any theme.json is readable).
            write(SHELL_DEFAULTS, ".pragma library\n// {}\n// Polar night, the default theme, used until a theme.json can be read.\nvar THEME = {};\n".format(
                HEADER, theme_json(tok, folder, key, scheme, wp, lock_wp).rstrip()))
            print("wrote", os.path.relpath(SHELL_DEFAULTS, ROOT))


if __name__ == "__main__":
    main()
