"""Render a palette into a theme directory.

Templates (templates/**/<file>.tmpl -> <theme>/<file>) cover the per-app files. Four outputs
are code, because the template language (deliberately) has no logic:

  theme.json    every design token for the Quickshell shell (colours as QML #AARRGGBB, type,
                spacing, radius, motion…) — non-colour tokens come from arctic-tokens.json
  gtk.css       the design's GTK export (exports/gtk-arctic-<base>.css) with the palette's
                colours; 8-digit hex becomes rgba(), which GTK3 CSS needs
  theme.env     sourced by the arctic-* shell scripts, so values are shell-quoted
  icons/*.svg   the design icons recoloured to the palette's ink, plus the 16px mark

plus palette.json, the palette itself (arctic-theme and the Settings app read it).
"""
import json
import os
import re
import shlex
import tempfile

from . import color, template
from .palette import PKG_DIR, ROLES, ThemegenError, data_dir, dumps, tokens, validate

TEMPLATES_DIR = os.path.join(PKG_DIR, "templates")
CODE_OUTPUTS = ("theme.json", "gtk.css", "theme.env", "palette.json")
# Icons that sit at rest in ink-muted (quiet bar items); everything else uses ink.
MUTED_ICONS = {"bell", "bell-off", "bluetooth"}
# The design exports its icons in charcoal ink.
ICON_INK = "#151a21"


def header(p):
    return "Generated by arctic-themegen from the {} palette — do not edit by hand.".format(p["label"])


# ---- theme.json -------------------------------------------------------------------------------

def camel(name):
    """design token name -> QML property name: surface-raised -> surfaceRaised, ansi-0 -> ansi0."""
    head, *rest = name.split("-")
    return head + "".join(part[:1].upper() + part[1:] for part in rest)


def qml_color(c):
    """#rrggbb stays; CSS #rrggbbaa -> QML #aarrggbb."""
    c = c.lower()
    if len(c) == 9:
        return "#" + c[7:9] + c[1:7]
    return c


def px(v):
    """'12px' -> 12, '120ms' -> 120, '-0.02em' -> -0.02 (numbers pass through)."""
    if isinstance(v, (int, float)):
        return v
    m = re.match(r"^(-?[0-9.]+)", str(v))
    n = float(m.group(1)) if m else 0
    return int(n) if n == int(n) else n


def bezier(v):
    """'cubic-bezier(0.2, 0, 0, 1)' -> [0.2, 0, 0, 1]."""
    return [px(x.strip()) for x in re.findall(r"\((.*)\)", v)[0].split(",")]


def theme_json(p):
    """All tokens the Quickshell shell needs, in one file per theme (QML colour order)."""
    tok = tokens()
    dark = p["mode"] == "dark"
    colors = {camel(r): qml_color(p["colors"][r]) for r in ROLES}
    for k, v in tok["ramps"].items():
        colors[camel(k)] = qml_color(v)
    extra = {"contrast": "high"} if p.get("contrast") == "high" else {}
    return json.dumps(dict({
        "_comment": header(p) + " Colours are QML #AARRGGBB.",
        "id": p["name"],
        "name": p["label"],
        "dark": dark,
        "colorScheme": "prefer-dark" if dark else "prefer-light",
        "wallpaper": p["wallpaper"],
        "lockWallpaper": p["lock_wallpaper"],
        "colors": colors,
        "fonts": dict(tok["font"]),
        "type": {camel(k): {"size": px(v["fontSize"]), "lineHeight": px(v["lineHeight"]),
                            "weight": v["fontWeight"], "family": v["family"],
                            "letterSpacing": px(v.get("letterSpacing", 0))}
                 for k, v in tok["type"].items()},
        "spacing": {camel(k.replace("-0-5", "Half")): px(v) for k, v in tok["spacing"].items()},
        "radius": {camel(k): px(v) for k, v in tok["radius"].items()},
        "border": {camel(k): px(v) for k, v in tok["border"].items()},
        "blur": {camel(k): px(v) for k, v in tok["blur"].items()},
        "size": {camel(k): px(v) for k, v in tok["size"].items()},
        "duration": {camel(k): px(v) for k, v in tok["duration"].items()},
        "easing": {camel(k): bezier(v) for k, v in tok["easing"].items()},
    }, **extra), indent=1, sort_keys=False) + "\n"


# ---- gtk.css ------------------------------------------------------------------------------------

def css_rgba(c):
    """#rrggbbaa -> rgba(r, g, b, a) for GTK CSS, which lacks 8-digit hex on older GTK3."""
    (r, g, b), a = color.parse_hex(c)
    return "rgba({}, {}, {}, {:.2f})".format(r, g, b, 1.0 if a is None else a / 255)


def gtk_css(p):
    """The design's GTK export for the palette's base (or its mode's built-in theme), with every
    @define-color arctic_<role> set from the palette."""
    base = p["base"] if p["base"] in ("winter", "polar-night") else ("polar-night" if p["mode"] == "dark" else "winter")
    path = os.path.join(data_dir(), "exports", "gtk-arctic-{}.css".format(base))
    with open(path, encoding="utf-8") as f:
        css = f.read()
    colors = p["colors"]

    def role_value(m):
        role = m.group(1).replace("_", "-")
        return m.group(0) if role not in colors else "@define-color arctic_{} {};".format(m.group(1), colors[role])

    css = re.sub(r"@define-color arctic_([a-z0-9_]+) [^;]*;", role_value, css)
    css = css.replace("GTK colours — {}.".format(base), "GTK colours — {}.".format(p["name"]), 1)
    # GTK CSS has no 8-digit hex (#rrggbbaa), so translucent colours become rgba().
    return re.sub(r"#([0-9a-fA-F]{8})\b", lambda m: css_rgba("#" + m.group(1)), css)


# ---- theme.env ----------------------------------------------------------------------------------

def _dq(s):
    """Double-quoted shell word."""
    return '"' + re.sub(r'(["\\$`])', r"\\\1", s) + '"'


def theme_env(p):
    dark = p["mode"] == "dark"
    return "\n".join([
        "# " + header(p),
        "ARCTIC_THEME=" + shlex.quote(p["name"]),
        "ARCTIC_THEME_NAME=" + _dq(p["label"]),
        "ARCTIC_GROUND=" + _dq(template.apply_filter(p["colors"]["ground"], "hex")),
        "ARCTIC_COLOR_SCHEME=" + ("prefer-dark" if dark else "prefer-light"),
        "ARCTIC_GTK_PREFER_DARK=" + ("1" if dark else "0"),
        "ARCTIC_WALLPAPER=" + shlex.quote(p["wallpaper"]),
        "ARCTIC_LOCK_WALLPAPER=" + shlex.quote(p["lock_wallpaper"]),
        "ARCTIC_THEME_MODE=" + p["mode"],
        "ARCTIC_THEME_BASE=" + shlex.quote(p["base"]),
    ]) + "\n"


# ---- icons --------------------------------------------------------------------------------------

def icons(p):
    """{relative path: svg text} for icons/."""
    src = os.path.join(data_dir(), "icons")
    colors = p["colors"]
    ink = template.apply_filter(colors["ink"], "hex")
    muted = template.apply_filter(colors["ink-muted"], "hex")
    out = {}
    for fn in sorted(os.listdir(src)):
        if not fn.endswith(".svg"):
            continue
        with open(os.path.join(src, fn), encoding="utf-8") as f:
            svg = f.read()
        out["icons/" + fn] = re.sub(re.escape(ICON_INK), muted if fn[:-4] in MUTED_ICONS else ink, svg, flags=re.IGNORECASE)
    # The on-accent variant used on the amber Install item.
    with open(os.path.join(src, "download.svg"), encoding="utf-8") as f:
        out["icons/download-on-accent.svg"] = re.sub(re.escape(ICON_INK), template.apply_filter(colors["on-accent"], "hex"),
                                                      f.read(), flags=re.IGNORECASE)
    # The 16px drawing of the mark (no eyes, wider gap) for the bar: charcoal on light themes,
    # snow on dark ones.
    mark = os.path.join(data_dir(), "logos", "arctic-mark-16-{}.svg".format("snow" if p["mode"] == "dark" else "charcoal"))
    with open(mark, encoding="utf-8") as f:
        out["icons/mark.svg"] = f.read()
    return out


# ---- templates ----------------------------------------------------------------------------------

def template_files(dirs):
    """{output relative path: template path}; later directories override earlier ones."""
    found = {}
    for d in dirs:
        if not os.path.isdir(d):
            continue
        for root, subdirs, files in os.walk(d):
            subdirs.sort()
            for fn in sorted(files):
                if not fn.endswith(".tmpl"):
                    continue
                path = os.path.join(root, fn)
                rel = os.path.relpath(path, d)[:-len(".tmpl")].replace(os.sep, "/")
                if rel in CODE_OUTPUTS or rel.startswith("icons/"):
                    raise ThemegenError("{}: '{}' is generated by the engine and can't be a template".format(path, rel))
                found[rel] = path
    return found


def outputs(palette, template_dirs=()):
    """Every file of the theme as {relative path: text}."""
    p = validate(palette)
    colors, scalars = template.context(p, tokens().get("font", {}))
    files = {}
    for rel, path in sorted(template_files([TEMPLATES_DIR] + list(template_dirs)).items()):
        with open(path, encoding="utf-8") as f:
            text = f.read()
        files[rel] = template.render(text, colors, scalars, where=path)
    files["gtk.css"] = gtk_css(p)
    files["theme.env"] = theme_env(p)
    files.update(icons(p))
    files["palette.json"] = dumps(p)
    files["theme.json"] = theme_json(p)
    return files


# ---- writing ------------------------------------------------------------------------------------

def _write_atomic(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    try:
        with open(path, "rb") as f:
            if f.read() == data:
                return False
    except OSError:
        pass
    fd, tmp = tempfile.mkstemp(prefix=".tmp-", dir=os.path.dirname(path))
    try:
        with os.fdopen(fd, "wb") as f:
            f.write(data)
        os.chmod(tmp, 0o644)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise
    return True


def render(palette, out_dir, template_dirs=(), force=False):
    """Write the theme for `palette` into out_dir. Files are replaced one by one (atomically), so
    a theme in use never has a missing or half-written file; theme.json goes last (the shell
    reloads when it changes). Files a previous render left and this one doesn't make are removed.

    out_dir must be missing, empty, or a theme directory (it has palette.json); force=True
    renders into any directory (and then removes files the theme doesn't have).
    Returns the list of files written (relative paths)."""
    files = outputs(palette, template_dirs)
    out_dir = os.path.abspath(out_dir)
    existing = []
    if os.path.isdir(out_dir):
        for root, _dirs, fns in os.walk(out_dir):
            for fn in fns:
                existing.append(os.path.relpath(os.path.join(root, fn), out_dir).replace(os.sep, "/"))
        if existing and "palette.json" not in existing and not force:
            raise ThemegenError("{} is not a theme directory (no palette.json); "
                                "pass --force to render into it anyway".format(out_dir))
    elif os.path.exists(out_dir):
        raise ThemegenError("{} exists and is not a directory".format(out_dir))
    written = []
    order = sorted(k for k in files if k != "theme.json") + ["theme.json"]
    for rel in order:
        if _write_atomic(os.path.join(out_dir, rel), files[rel].encode("utf-8")):
            written.append(rel)
    for rel in existing:
        if rel not in files:
            os.unlink(os.path.join(out_dir, rel))
    # Drop directories the stale files leave empty.
    for root, dirs, fns in sorted(os.walk(out_dir, topdown=False), key=lambda t: -len(t[0])):
        if root != out_dir and not os.listdir(root):
            os.rmdir(root)
    return written
