# Arctic's wlroots desktop uses GTK for settings (including light/dark) and file dialogs,
# and wlr for the compositor's screen capture and sharing.
[preferred]
default=gtk
org.freedesktop.impl.portal.Settings=gtk
org.freedesktop.impl.portal.ScreenCast=wlr
org.freedesktop.impl.portal.Screenshot=wlr
