id = "inkscape"
name = "Inkscape"
summary = "Vector drawing."
category = "extras"
role = "drawing app"
default = false
tile = "inkscape"
icon = "pen-nib"
in_live_image = false
gpu = true
requires = []
conflicts = []

[[install]]
method = "flatpak"
remote = "flathub"
ref = "org.inkscape.Inkscape"
runtime = "org.gnome.Platform//50"
verified = true
download_mb = 98
